//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Android_KingHoo_Scanner_Rebuild {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Res() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Android_KingHoo_Scanner_Rebuild.Resource_Res", typeof(Resource_Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] wait {
            get {
                object obj = ResourceManager.GetObject("wait", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE PROCEDURE [dbo].[ZZ_KIngHoo_LookUpInventory]
        ///@FNumber NVARCHAR(80)
        ///AS
        ///BEGIN
        ///EXEC dbo.CheckInventory
        ///SELECT C.FName [仓库/单据],D.FName 仓位,CAST(CAST(A.FQty AS DECIMAL(20,2)) AS NVARCHAR(20))+ E.FName 主计量,
        ///CAST(CAST(A.FSecQty AS DECIMAL(20,2)) AS nvarchar(20)) +F.FName 辅助计量,A.FBatchNo 批号
        ///  FROM dbo.ICInventory A 
        ///JOIN dbo.t_ICItem B ON A.FItemID=B.FItemID 
        ///JOIN dbo.t_Stock C ON A.FStockID=C.FItemID
        ///LEFT JOIN dbo.t_StockPlace D ON A.FStockPlaceID=D.FSPID
        ///LEFT JOIN dbo.t_MeasureUnit E ON B.FUnitID [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ZZ_KIngHoo_LookUpInventory {
            get {
                return ResourceManager.GetString("ZZ_KIngHoo_LookUpInventory", resourceCulture);
            }
        }
    }
}
